### ISSUE TITLE
"Permission denied" When running install.sh for SKOS Demo

### ISSUE THREAD

**Issue by tmciver** [AtomGraph/LinkedDataHub-Apps#2]
After making `demo/skos/install.sh` executable with `chmod +x demo/skos/install.sh`, I get many "Permission denied" errors like the following:

```
### Creating authorization to make the app public

./install.sh: line 21: ./make-public.sh: Permission denied
```
Running the install script with `sudo` did not change the result.

Noticing [this line](https://github.com/AtomGraph/LinkedDataHub-Apps/blob/7fb4c476eb13847e04c01047fa119d12926cf70a/demo/skos/admin/make-public.sh#L14) I tried the following query from the command line:
```
curl -v -k -E /home/tim/workspace/linkeddata/linked-data-hub/certs/owner.p12.pem:<my-password> https://localhost:4443/admin/graphs/a86ce4fa-0197-4118-878e-32ea2d695878
```

but this resulted in the following error:
```
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 4443 (#0)
* found 127 certificates in /etc/ssl/certs/ca-certificates.crt
* found 513 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* error reading X.509 potentially-encrypted key file: Decryption has failed.
* Closing connection 0
curl: (35) error reading X.509 potentially-encrypted key file: Decryption has failed.
```
This was surprising since I'm sure this is the certificate that I'm using to connect to my local instance of LDH.  Also, when I go to `https://localhost:4443/admin/graphs` in a browser, I see `Query result Dataset is empty` so I don't think the above `curl` command would succeed even if there were not a certificate issue since `a86ce4fa-0197-4118-878e-32ea2d695878` does not seem to exist there.

**Comment by namedgraph** [comment]
The permissions problem seems to be similar to #1 . Can you try the steps described here?

I have trouble with this as I'm running Windows and executing shell commands through Windows Subsystem for Linux (WSL). I'll see what I can do about this.

**Comment by tmciver** [comment]
I'll take a look.  This problem may be due to my failure to set `SCRIPT_ROOT` before running the script.

**Comment by tmciver** [comment]
After setting `SCRIPT_ROOT` and making all scripts executable, this error was no longer happening.
