### ISSUE TITLE
Missing `create-construct.sh`

### ISSUE THREAD

**Issue by tmciver** [AtomGraph/LinkedDataHub-Apps#3]
The `create-construct.sh` script referenced [here](https://github.com/AtomGraph/LinkedDataHub-Apps/blob/7fb4c476eb13847e04c01047fa119d12926cf70a/demo/skos/admin/model/create-constructors.sh#L20) does not seem to exist anywhere in the code base.

**Comment by namedgraph** [comment]
This is the script: https://github.com/AtomGraph/LinkedDataHub/blob/master/scripts/admin/model/create-construct.sh

Is the execution failing? Do you have a log?

**Comment by namedgraph** [comment]
Good catch re. `$SCRIPT_ROOT`! Looks like it's an omission on our part.

I've added Prerequisites section to the README: https://github.com/AtomGraph/LinkedDataHub-Apps#prerequisites
Is that sufficient?

**Comment by tmciver** [comment]
Yes, looks good.
